# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-21 16:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastros_basicos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1)),
                ('data_nascimento', models.DateField()),
                ('rg', models.CharField(blank=True, max_length=20, null=True, verbose_name='RG')),
                ('cpf', models.CharField(blank=True, max_length=20, null=True, verbose_name='CPF')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('numero_celular', models.CharField(max_length=11, verbose_name='Celular')),
                ('numero_fixo', models.CharField(max_length=11, verbose_name='Fixo')),
                ('endereco_completo', models.CharField(blank=True, max_length=150, null=True, verbose_name='Endereço completo')),
                ('nome_do_responsavel', models.CharField(blank=True, max_length=100, null=True)),
                ('contato_do_responsavel', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_da_mensalidade', models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Valor mensalidade do aluno')),
                ('data_matricula', models.DateField()),
                ('situacao_matricula', models.PositiveIntegerField(choices=[(1, 'Ativa'), (2, 'Suspensa')])),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alunos.Aluno')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros_basicos.Turma')),
            ],
        ),
    ]
