# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-22 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matricula',
            name='valor_da_mensalidade',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Valor mensalidade do aluno'),
        ),
    ]
