# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-27 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0002_auto_20160922_1608'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aluno',
            options={'verbose_name': 'Aluno(a)', 'verbose_name_plural': 'Alunos(as)'},
        ),
        migrations.AlterModelOptions(
            name='matricula',
            options={'verbose_name': 'Matrícula', 'verbose_name_plural': 'Matrículas'},
        ),
        migrations.AlterField(
            model_name='matricula',
            name='data_matricula',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='situacao_matricula',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Ativa'), (2, 'Suspensa')], default=1),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='valor_da_mensalidade',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Valor mensalidade do aluno'),
        ),
    ]
