# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-11 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0003_auto_20160927_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matricula',
            name='data_matricula',
            field=models.DateField(),
        ),
    ]
