# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-21 16:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alunos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensalidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes_referencia', models.PositiveIntegerField(choices=[(1, 'Janeiro'), (2, 'Fevereiro'), (3, 'Março'), (4, 'Abril'), (5, 'Maio'), (6, 'Junho'), (7, 'Julho'), (8, 'Agosto'), (9, 'Setembro'), (10, 'Outubro'), (11, 'Novembro'), (12, 'Dezembro')])),
                ('ano_referencia', models.PositiveIntegerField()),
                ('data_pagamento', models.DateField()),
                ('valor_cobrado', models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Valor cobrado')),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alunos.Matricula')),
            ],
        ),
    ]
