# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-24 19:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0002_auto_20160927_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensalidade',
            name='data_pagamento',
            field=models.DateField(null=True),
        ),
    ]
