# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-21 16:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Modalidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50, unique=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name_plural': 'Modalidades',
            },
        ),
        migrations.CreateModel(
            name='OfertaDeTurma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_da_mensalidade', models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Valor da mensalidade')),
                ('modalidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros_basicos.Modalidade')),
            ],
        ),
        migrations.CreateModel(
            name='Periodicidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=30, unique=True, verbose_name='Periodicidade por semana')),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1)),
            ],
            options={
                'verbose_name_plural': 'Professores',
            },
        ),
        migrations.CreateModel(
            name='Promocao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=30, unique=True, verbose_name='Valor promocional')),
            ],
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario', models.TimeField(blank=True, null=True)),
                ('oferta_de_turma', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='turmas_da_modalidade', to='cadastros_basicos.OfertaDeTurma')),
                ('professor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turmas_do_professor', to='cadastros_basicos.Professor')),
            ],
            options={
                'verbose_name_plural': 'Turmas',
            },
        ),
        migrations.AddField(
            model_name='ofertadeturma',
            name='periodicidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros_basicos.Periodicidade', verbose_name='Vezes por semana'),
        ),
        migrations.AddField(
            model_name='ofertadeturma',
            name='promocao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros_basicos.Promocao'),
        ),
    ]
