# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-22 15:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros_basicos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modalidade',
            options={'verbose_name': 'Modalidade', 'verbose_name_plural': 'Modalidades'},
        ),
        migrations.AlterModelOptions(
            name='ofertadeturma',
            options={'verbose_name': 'Oferta de Turma', 'verbose_name_plural': 'Ofertas de Turma'},
        ),
        migrations.AlterModelOptions(
            name='periodicidade',
            options={'verbose_name': 'Período', 'verbose_name_plural': 'Períodos'},
        ),
        migrations.AlterModelOptions(
            name='professor',
            options={'verbose_name': 'Professor', 'verbose_name_plural': 'Professores'},
        ),
        migrations.AlterModelOptions(
            name='promocao',
            options={'verbose_name': 'Promoção', 'verbose_name_plural': 'Promoções'},
        ),
        migrations.AlterModelOptions(
            name='turma',
            options={'verbose_name': 'Turma', 'verbose_name_plural': 'Turmas'},
        ),
        migrations.RemoveField(
            model_name='turma',
            name='oferta_de_turma',
        ),
        migrations.AddField(
            model_name='turma',
            name='modalidade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='turmas_da_modalidade', to='cadastros_basicos.Modalidade'),
        ),
        migrations.AddField(
            model_name='turma',
            name='tipo_turma',
            field=models.PositiveIntegerField(choices=[(1, 'misto'), (2, 'feminino'), (3, 'kids')], default=1),
        ),
    ]
