# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-22 15:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros_basicos', '0002_auto_20160922_1547'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ofertadeturma',
            options={'verbose_name': 'Valor da Mensalidade', 'verbose_name_plural': 'Valores das Mensalidades'},
        ),
        migrations.AlterField(
            model_name='ofertadeturma',
            name='promocao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros_basicos.Promocao', verbose_name='Tipo de promoção'),
        ),
        migrations.AlterField(
            model_name='ofertadeturma',
            name='valor_da_mensalidade',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Valor da mensalidade'),
        ),
    ]
