# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-27 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros_basicos', '0003_auto_20160922_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ofertadeturma',
            name='valor_da_mensalidade',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Valor da mensalidade'),
        ),
        migrations.AlterField(
            model_name='turma',
            name='tipo_turma',
            field=models.PositiveSmallIntegerField(choices=[(1, 'misto'), (2, 'feminino'), (3, 'kids')], default=1),
        ),
    ]
