# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-11 14:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros_basicos', '0004_auto_20160927_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ofertadeturma',
            name='modalidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofertas_da_modalidade', to='cadastros_basicos.Modalidade'),
        ),
    ]
