# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-12 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros_basicos', '0005_auto_20161011_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='dias_de_aula',
            field=models.PositiveSmallIntegerField(choices=[(1, '2ª, 4ª e 6ª feira'), (2, '3ª e 5ª feira')], default=1),
        ),
    ]
